# -*- coding: utf-8 -*-
"""Comvis v1.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGW1gwiYgezzGG0szc3id-m0onVWYOBV
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import time
import copy
import json

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, random_split
from torchvision import datasets, models, transforms

DATA_DIR = "/content/drive/MyDrive/Dataset1"

USE_TRAIN_VAL_SUBFOLDER = False

BATCH_SIZE = 16
NUM_EPOCHS = 15
LEARNING_RATE = 3e-4
IMG_SIZE = 224

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", DEVICE)

# Lokasi simpan model & nama kelas
MODEL_SAVE_PATH = os.path.join(DATA_DIR, "batik_resnet18_best.pth")
CLASS_NAMES_PATH = os.path.join(DATA_DIR, "batik_class_names.json")
print("Model akan disimpan di:", MODEL_SAVE_PATH)

def get_dataloaders():
    print("Mempersiapkan data dengan Augmentasi...")

    train_transform = transforms.Compose([
        transforms.Resize((256, 256)),
        transforms.RandomResizedCrop(IMG_SIZE, scale=(0.8, 1.0)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomVerticalFlip(),
        transforms.RandomRotation(30),
        transforms.ColorJitter(brightness=0.2, contrast=0.2),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])

    val_transform = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])

    if USE_TRAIN_VAL_SUBFOLDER:
        train_dataset = datasets.ImageFolder(root=os.path.join(DATA_DIR, "train"), transform=train_transform)
        val_dataset   = datasets.ImageFolder(root=os.path.join(DATA_DIR, "val"), transform=val_transform)
    else:
        if not os.path.exists(DATA_DIR):
            raise FileNotFoundError(f"Folder tidak ditemukan: {DATA_DIR}")

        full_dataset = datasets.ImageFolder(root=DATA_DIR, transform=train_transform)
        val_ratio = 0.2
        val_size  = int(len(full_dataset) * val_ratio)
        train_size = len(full_dataset) - val_size
        train_dataset, val_dataset = random_split(full_dataset, [train_size, val_size])

        val_dataset.dataset = copy.deepcopy(full_dataset)
        val_dataset.dataset.transform = val_transform

    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
    val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

    if USE_TRAIN_VAL_SUBFOLDER:
        class_names = train_dataset.classes
    else:
        class_names = full_dataset.classes

    return train_loader, val_loader, class_names

def build_model(num_classes):
    print(f"Membuat model ResNet18 untuk {num_classes} kelas...")
    model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)

    in_features = model.fc.in_features

    model.fc = nn.Sequential(
        nn.Dropout(0.5),
        nn.Linear(in_features, 512),
        nn.ReLU(),
        nn.Dropout(0.3),
        nn.Linear(512, num_classes)
    )
    return model

from tqdm import tqdm
def train_model():
    try:
        train_loader, val_loader, class_names = get_dataloaders()
        print(f"Kelas terdeteksi: {class_names}")

        with open(CLASS_NAMES_PATH, 'w') as f:
            json.dump(class_names, f)

        model = build_model(len(class_names)).to(DEVICE)

        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)

        scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', patience=3, factor=0.1)

        best_acc = 0.0

        print(f"\n🚀 MULAI TRAINING di device: {DEVICE}...")
        for epoch in range(NUM_EPOCHS):
            print(f"Epoch {epoch+1}/{NUM_EPOCHS}")
            print("-" * 10)

            model.train()
            train_loss = 0.0
            train_correct = 0

            for inputs, labels in tqdm(train_loader, desc="Training"):
                inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)

                optimizer.zero_grad()
                outputs = model(inputs)
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()

                train_loss += loss.item() * inputs.size(0)
                _, preds = torch.max(outputs, 1)
                train_correct += torch.sum(preds == labels.data)

            epoch_train_loss = train_loss / len(train_loader.dataset)
            epoch_train_acc = train_correct.double() / len(train_loader.dataset)

            model.eval()
            val_loss = 0.0
            val_correct = 0

            with torch.no_grad():
                for inputs, labels in val_loader:
                    inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
                    outputs = model(inputs)
                    loss = criterion(outputs, labels)

                    val_loss += loss.item() * inputs.size(0)
                    _, preds = torch.max(outputs, 1)
                    val_correct += torch.sum(preds == labels.data)

            epoch_val_loss = val_loss / len(val_loader.dataset)
            epoch_val_acc = val_correct.double() / len(val_loader.dataset)

            print(f"Train Loss: {epoch_train_loss:.4f} Acc: {epoch_train_acc:.4f}")
            print(f"Val Loss:   {epoch_val_loss:.4f} Acc: {epoch_val_acc:.4f}")

            last_lr = optimizer.param_groups[0]['lr']
            scheduler.step(epoch_val_loss)
            new_lr = optimizer.param_groups[0]['lr']

            if new_lr != last_lr:
                print(f"ℹ️ Learning Rate turun dari {last_lr} ke {new_lr}")

            if epoch_val_acc > best_acc:
                best_acc = epoch_val_acc
                torch.save(model.state_dict(), MODEL_SAVE_PATH)
                torch.save(model, os.path.join(DATA_DIR, "batik_model_full.pth"))
                print(f"💾 Model Disimpan! Best Acc: {best_acc:.4f}")

        print(f"\n✅ Training Selesai. Akurasi Terbaik: {best_acc:.4f}")

    except Exception as e:
        print(f"\n❌ TERJADI ERROR: {e}")

train_model()